### ISSUE TITLE
Unable to npm install roboticscape

### ISSUE THREAD

**Issue by mossfrond** [jadonk/node-roboticscape#2]
Under  latest BB image, 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux 

# npm install https://github.com/jadonk/
/
> roboticscape@0.0.3 install /root/chopper/node_modules/roboticscape
> node-gyp rebuild

make: Entering directory '/root/chopper/node_modules/roboticscape/build'
  CXX(target) Release/obj.target/roboticscape/rc-node-bindings.o
../rc-node-bindings.cc: In function ‘void rc::RCexit(void*)’:
../rc-node-bindings.cc:21:47: error: cannot convert ‘const char*’ to ‘FILE* {aka _IO_FILE*}’ for argument ‘1’ to ‘int fprintf(FILE*, const char*, ...)’
         fprintf("info: running rc_cleanup()\n");
                                               ^
roboticscape.target.mk:96: recipe for target 'Release/obj.target/roboticscape/rc-node-bindings.o' failed
make: *** [Release/obj.target/roboticscape/rc-node-bindings.o] Error 1
make: Leaving directory '/root/chopper/node_modules/roboticscape/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.4.54-ti-r93
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/chopper/node_modules/roboticscape
gyp ERR! node -v v4.8.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.4.54-ti-r93
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "https://github.com/jadonk/node-roboticscape"
npm ERR! node v4.8.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! roboticscape@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the roboticscape@0.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the roboticscape package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs roboticscape
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls roboticscape
npm ERR! There is likely additional logging output above.

**Comment by jadonk** [comment]
Sorry for the delay. Should be fixed now.
